In [5]:
import numpy as np

# Arrays

In [38]:
# creating ndarray from list
# every element must have same data type (will be converted is possible)
data1=[1,2,3,4,5] # list 
arr1=np.array(data1)
print(data1, type(data1))
print(arr1, type(arr1))

[1, 2, 3, 4, 5] <class 'list'>
[1 2 3 4 5] <class 'numpy.ndarray'>


In [40]:
data1=[1,2.2,3,4,5]
arr1=np.array(data1)
print(data1, type(data1))
print(arr1, type(arr1))

[1, 2.2, 3, 4, 5] <class 'list'>
[1.  2.2 3.  4.  5. ] <class 'numpy.ndarray'>


In [42]:
data2=[range(1,5),range(5,9)]
print(data2 ,type(data2))
arr2=np.array(data2)
print(arr2, type(arr2))

[range(1, 5), range(5, 9)] <class 'list'>
[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'>


In [44]:
# converting ndarray to list
list2=arr2.tolist()
print(list2 ,type(list2))

[[1, 2, 3, 4], [5, 6, 7, 8]] <class 'list'>


In [46]:
print(list(range(1,5)))

[1, 2, 3, 4]


In [48]:
# Examing arrays  ndim-> no of dimendion, size->total no of element, len->size of first dimension
print(arr1,type(arr1),id(arr1),arr1.dtype,arr1.ndim,arr1.shape,type(arr1.shape),arr1.size,len(arr1))
print(arr2,type(arr2),id(arr2),arr2.dtype,arr2.ndim,arr2.shape,type(arr2.shape),arr2.size,len(arr2))


[1.  2.2 3.  4.  5. ] <class 'numpy.ndarray'> 1767532216368 float64 1 (5,) <class 'tuple'> 5 5
[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'> 1767532216752 int32 2 (2, 4) <class 'tuple'> 8 2


In [50]:
a=np.array([7+9j,3-25j,5,7],dtype=complex)
a

array([7. +9.j, 3.-25.j, 5. +0.j, 7. +0.j])

In [54]:
print(a[0],a[2])

(7+9j) (5+0j)


In [64]:
# find min, max and sum of array
a=np.array([1,2,3,10,15,4])  
print("array=",a)
print(f"max={a.max()} , min={a.min()} , sum={a.sum()}")

array= [ 1  2  3 10 15  4]
max=15 , min=1 , sum=35


In [74]:
# find the square-root and standard deviation of the array
a=np.array([[1,2,30],[10,15,4]])
print("array=",a)
print(f'{np.sqrt(a)}')
print(f'{np.std(a)}')

array= [[ 1  2 30]
 [10 15  4]]
[[1.         1.41421356 5.47722558]
 [3.16227766 3.87298335 2.        ]]
10.044346115546242


In [78]:
# multiply 2 array each element with specific index
a=np.array([1,2,3,4,5,6,7])
b=np.array([2,4,6,8,10,12,14]) # it should be same order
c=a*b
print(c)

[ 2  8 18 32 50 72 98]


In [94]:
a=np.array([[1,2,3,4],[2,4,5,6],[10,20,30,40]])
b=np.array([1,2,6,8])
print("printing array a...\n",a)
print("printing array b...\n",b)
c=a+b
print("printing array c...\n",c)

printing array a...
 [[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 30 40]]
printing array b...
 [1 2 6 8]
printing array c...
 [[ 2  4  9 12]
 [ 3  6 11 14]
 [11 22 36 48]]


In [96]:
# numpy array iteration
a=np.array([[1,2,3,4],[2,4,5,6],[6,10,30,40]])
for x in np.nditer(a):
    print(x,end=",")

1,2,3,4,2,4,5,6,6,10,30,40,

### 3-D Array

In [107]:
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr,arr.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 3


In [115]:
# bitwise And and Or operation
a=10
b=12
print(f"binary representation of a={bin(a)}")
print(f"binary representation of b={bin(b)}")
print(f"Bitwise-and of a and b={np.bitwise_and(a,b)}")
print(f"Bitwise-and of a or b={np.bitwise_or(a,b)}")

binary representation of a=0b1010
binary representation of b=0b1100
Bitwise-and of a and b=8
Bitwise-and of a or b=14


#### Higher Dimensional Arrays(using the ndmin argument)

In [7]:
a=np.array([1,2,3,4,5],ndmin=5)
print(a,a.ndim)

[[[[[1 2 3 4 5]]]]] 5


#### Indexing

In [14]:
a=np.array([1,2,3,4])
print(a[0])
print(a[2]+a[3])

1
7


In [12]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a[0,1])
print(a[1,2])

[[1 2 3]
 [4 5 6]]
2
6


### Slicing in Numpy

In [21]:
# [start:end],[start:end:step]
a=np.array([1,2,3,4,5])
print(a[1:4])
print(a[2:])

# negative slicing
print(a[-4:-1])
print(a[::-1])
print(a[::2])

[2 3 4]
[3 4 5]
[2 3 4]
[5 4 3 2 1]
[1 3 5]


In [27]:
# Slicing 2-D Arrays
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a[1,1:4])
print(a[0:2,2])
print(a[0:2,1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


In [43]:
# Finding maximum columnise and rowise
a=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print("array:",a)
print("max ele in cols:",a.max(axis=0)) # axis=0 means column wise
print("max ele in rows:",a.max(axis=1)) # axis=1 means row wise
print("min ele in cols:",a.min(axis=0))
print("min ele in rows:",a.min(axis=0))
print("diagonal ele of matrix:",a.diagonal())

array: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
max ele in cols: [21 22 23 24 25]
max ele in rows: [ 5 10 15 20 25]
min ele in cols: [1 2 3 4 5]
min ele in rows: [1 2 3 4 5]
diagonal ele of matrix: [ 1  7 13 19 25]


In [45]:
# Right Diagonal Elements
flip=np.fliplr(a)
print(flip.diagonal())

[ 5  9 13 17 21]


### Transpose of Matrix

In [54]:
# Original Matrix
print(a)
print()
# Transpose Matrix
# arr1=a.T
# arr1=a.transpose()
arr1=np.transpose(a)
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

[[ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]
 [ 5 10 15 20 25]]


In [83]:
# create special arrays
print(np.zeros(15))
print(np.zeros((3,6),dtype=int))
print()
print(np.zeros((3,6)).astype(int))
print(np.linspace(1,100,10)) # 0 to 1 (inclusive) with 5 point
print()
print(np.logspace(0,3,4).astype(int)) # 10^0 to 10^3 (inclusive)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]

[   1   10  100 1000]


In [96]:
print(np.ones(5))
print(np.ones((3,6),dtype=int))
print(np.ones((3,6),dtype=bool))
print(np.zeros((3,6),dtype=bool))

[1. 1. 1. 1. 1.]
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]
[[False False False False False False]
 [False False False False False False]
 [False False False False False False]]


In [102]:
# Tile for repeating numbers
original_array=np.array([1,2,3])
print("original array:",original_array)
tiled_array=np.tile(original_array,(4,3))
print("\nTiled array:",tiled_array)

original array: [1 2 3]

Tiled array: [[1 2 3 1 2 3 1 2 3]
 [1 2 3 1 2 3 1 2 3]
 [1 2 3 1 2 3 1 2 3]
 [1 2 3 1 2 3 1 2 3]]


In [104]:
# Array for specified Numbers
a=np.full([4,4],2)
print(a)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


### Flower Graphics

In [ ]:
import turtle as tur
import colorsys as cs
tur.setup(800,800)
tur.speed(0)
tur.tracer(10)
tur.width(2)
tur.bgcolor("black")

for i in range(25):
    for j in range(15):
        tur.color(cs.hsv_to_rgb(i/15,j/25,1))
        tur.right(90)
        tur.circle(200-j*4,90)
        tur.left(90)
        tur.circle(200-j*4,90)
        tur.right(180)
        tur.circle(50,24)
tur.hideturtle()
tur.done()